// localStorage.clear()
const employees = [
  {
    id: 1,
    FirstName: "Amit Sharma",
    email: "amit.sharma@example.com",
    password: "123",
    designation: "Software Developer",
    location: "Bangalore",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed:0,
      failed: 0,
      hold: 0,
      accepted: 1,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Update website",
        taskDescription: "Revamp the homepage design",
        taskDate: "2024-10-12",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        hold: false,
        failed: false,
        accepted: false,
        taskTitle: "Client meeting",
        taskDescription: "Discuss project requirements",
        taskDate: "2024-10-10",
        category: "Meeting",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Fix bugs",
        taskDescription: "Resolve bugs reported in issue tracker",
        taskDate: "2024-10-14",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Update website",
        taskDescription: "Revamp the homepage design",
        taskDate: "2024-10-12",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        hold: false,
        failed: false,
        accepted: false,
        taskTitle: "Client meeting",
        taskDescription: "Discuss project requirements",
        taskDate: "2024-10-10",
        category: "Meeting",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Fix bugs",
        taskDescription: "Resolve bugs reported in issue tracker",
        taskDate: "2024-10-14",
        category: "Development",
      },
    ],
  },

  {
    id: 2,
    FirstName: "Priya Singh",
    email: "p@s.com",
    password: "123",
    designation: "Web Developer",
    location: "Mumbai",
    taskCounts: {
      active: 4,
      newTask: 2,
      completed: 3,
      failed: 0,
      hold: 2,
      accepted: 2,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Database optimization",
        taskDescription: "Optimize queries for better performance",
        taskDate: "2024-10-11",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Design new feature",
        taskDescription: "Create mockups for the new feature",
        taskDate: "2024-10-09",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Fix bugs",
        taskDescription: "Resolve bugs reported in issue tracker",
        taskDate: "2024-10-14",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Database optimization",
        taskDescription: "Optimize queries for better performance",
        taskDate: "2024-10-11",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Design new feature",
        taskDescription: "Create mockups for the new feature",
        taskDate: "2024-10-09",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Fix bugs",
        taskDescription: "Resolve bugs reported in issue tracker",
        taskDate: "2024-10-14",
        category: "Development",
      },
    ],
  },
  {
    id: 3,
    FirstName: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    password: "123",
    designation: "Data Analyst",
    location: "Delhi",
    taskCounts: {
      active: 4,
      newTask: 2,
      completed: 2,
      failed: 0,
      hold: 3,
      accepted: 4,
    },
    tasks: [
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Prepare presentation",
        taskDescription: "Prepare slides for upcoming client presentation",
        taskDate: "2024-10-13",
        category: "Presentation",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Code review",
        taskDescription: "Review the codebase for optimization",
        taskDate: "2024-10-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Testing",
        taskDescription: "Test the latest build for bugs",
        taskDate: "2024-10-08",
        category: "QA",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Prepare presentation",
        taskDescription: "Prepare slides for upcoming client presentation",
        taskDate: "2024-10-13",
        category: "Presentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        hold: false,
        failed: false,
        accepted: true,
        taskTitle: "Code review",
        taskDescription: "Review the codebase for optimization",
        taskDate: "2024-10-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Testing",
        taskDescription: "Test the latest build for bugs",
        taskDate: "2024-10-08",
        category: "QA",
      },
    ],
  },
  {
    id: 4,
    FirstName: "Sneha Patel",
    email: "sneha.patel@example.com",
    password: "123",
    designation: "Project Manager",
    location: "Ahmedabad",
    taskCounts: {
      active: 4,
      newTask: 2,
      completed: 2,
      failed: 0,
      hold: 2,
      accepted: 2,
    },
    tasks: [
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Write documentation",
        taskDescription: "Update the project documentation",
        taskDate: "2024-10-13",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Set up CI/CD",
        taskDescription: "Implement continuous integration pipeline",
        taskDate: "2024-10-11",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Testing",
        taskDescription: "Test the latest build for bugs",
        taskDate: "2024-10-08",
        category: "QA",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Write documentation",
        taskDescription: "Update the project documentation",
        taskDate: "2024-10-13",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Set up CI/CD",
        taskDescription: "Implement continuous integration pipeline",
        taskDate: "2024-10-11",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Testing",
        taskDescription: "Test the latest build for bugs",
        taskDate: "2024-10-08",
        category: "QA",
      },
    ],
  },
  {
    id: 5,
    FirstName: "Vikas Gupta",
    email: "vikas.gupta@example.com",
    password: "123",
    designation: "Quality Analyst",
    location: "Chennai",
    taskCounts: {
      active: 4,
      newTask: 2,
      completed: 1,
      failed: 0,
      hold: 2,
      accepted: 2,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        accepted: true,
        hold: true,
        taskTitle: "Deploy new build",
        taskDescription: "Deploy the latest build to production",
        taskDate: "2024-10-09",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        accepted: false,
        hold: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
    ],
  },
  {
    id: 6,
    FirstName: "Anjali Verma",
    email: "anjali.verma@example.com",
    password: "123",
    designation: "UI/UX Designer",
    location: "Pune",
    taskCounts: {
      active: 5,
      newTask: 1,
      completed: 1,
      failed: 0,
      hold: 1,
      accepted: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Deploy new build",
        taskDescription: "Deploy the latest build to production",
        taskDate: "2024-10-09",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: true,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
    ],
  },
  {
    id: 7,
    FirstName: "Manoj Desai",
    email: "manoj.desai@example.com",
    password: "123",
    designation: "Backend Developer",
    location: "Hyderabad",
    taskCounts: {
      active: 5,
      newTask: 1,
      completed: 1,
      failed: 0,
      hold: 3,
      accepted: 5,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        hold: false,
        accepted: true,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        active: false,
        newTask: true,
        completed: true,
        failed: false,
        hold: false,
        accepted: true,
        taskTitle: "Deploy new build",
        taskDescription: "Deploy the latest build to production",
        taskDate: "2024-10-09",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
    ],
  },
  {
    id: 8,
    FirstName: "Nisha Reddy",
    email: "nisha.reddy@example.com",
    password: "123",
    designation: "HR Executive",
    location: "Kolkata",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
      hold: 2,
      accepted: 2,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        hold: true,
        accepted: true,
        taskTitle: "Deploy new build",
        taskDescription: "Deploy the latest build to production",
        taskDate: "2024-10-09",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        hold: false,
        accepted: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    FirstName: "Vikrant Kushwaha",
    email: "vikrant.kushwaha@admin.com",
    password: "12345@AD",
    post: "System administrator",
    place: "New Delhi",
  },
  {
    id: 2,
    FirstName: "Priyanka",
    email: "priyanka@admin.com",
    password: "12345@AD",
    post: "Network administrator",
    place: "Bangalore",
  },
];
// console.log(admin,employees);

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
